data:
  series:
    - axt2
    - adc
    - b1500
  val_split: 0.2
  batch_size: 192 # 128
  num_workers: 4
  augment_data: false
  normalize: true
  zero_pad: true

paths:
  data_dir: "/gpfs/data/prostatelab/processed_data/h5/t2_dwi_filtered_20240212"
  train_csv: "/gpfs/data/prostatelab/processed_data/csv/data_split/train_temporal_split_20240619_exclude_mismatch.csv"
  valid_csv: /gpfs/data/prostatelab/processed_data/csv/data_split/val_temporal_split_20240619_exclude_mismatch.csv

train:
  epochs: 20
  model:
    name: MRI_ResNet18_3D
    pretrained: false
    num_classes: 5
    combine_adc_b1500: true
  binarize: true
  criterion: "ce"  # Loss function: "ce", "mse", or "bce"
  optimizer:
    name: "adam"  # Optimizer: "adam", "sgd", or "rmsprop"
    lr: 0.001
  scheduler:
    name: "cosine"  # Scheduler: "steplr", "exponentiallr", "reducelronplateau", "cosine", "onecycle", or "linear"

logging:
  wandb_project: "Prostate MRI Classification"
  wandb_log_files:
    - train.log
    - valid.log